#pragma once

#include <process.h>

namespace Client
{
	const unsigned int			g_iWinSizeX = { 1280 };
	const unsigned int			g_iWinSizeY = { 720 };

	enum LEVELID { LEVEL_STATIC, LEVEL_LOADING, LEVEL_LOGO, LEVEL_LOBBY, LEVEL_GAMEPLAY, LEVEL_MINIGAME, LEVEL_END };

	enum class PLAYER_DIR { LEFTDOWN, LEFTTOP, RIGHTDOWN, RIGHTTOP, DIR_END };
	enum class PLAYER_CHARACTER { PLAYER_CAT, PLAYER_DOG, PLAYER_PENGUIN, PLAYER_END };
	enum class PLAYER_STATE { STATE_IDLE, STATE_MOVE, STATE_ATTACK, STATE_MOVEATTACK, STATE_END };

	enum Bullet_ID { ID_PLAYER, FIRST_BOT, SECOND_BOT, THIRD_BOT, ID_END};

	enum class DIRECTION { LEFT, UP, RIGHT, DOWN, LU, LD, RU, RD, DR_END }; // 8πÊ«‚

	enum class CHANNELID {
		SOUND_EFFECT,
		SOUND_PLAYER_FIRE,
		SOUND_PLAYER_Hit,
		SOUND_PLAYER_LEVELUP,
		SOUND_PLAYER_SKILL,
		SOUND_DIE,
		SOUND_ATTACK,
		SOUND_BOSSFIGHTSTART,
		SOUND_HIT,
		SOUND_SCANNER,
		SOUND_EXPLOSIVE,
		SOUND_SKILL,
		SOUND_EXPITEM,
		SOUND_GETITEM,
		SOUND_Laser,
		SOUND_GAMEPLAY_START,
		SOUND_GAMEPLAY_DELAY,
		SOUND_BGM,
		SOUND_END
	};

	enum FONT_TYPE { FT_S_SMALL, FT_SMALL, FT_MIDDLE, FT_LARGE, FT_L_LARGE, FT_XL_LARGE, FT_END };
}

extern HWND g_hWnd;

using namespace Client;
using namespace std;
